# Generated by Django 5.0.2 on 2024-03-15 01:19

import django.core.validators
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='garantia',
            field=models.CharField(choices=[('1', '1 mes'), ('3', '3 meses'), ('6', '6 meses'), ('12', '1 año')], default='0', max_length=2, verbose_name='Garantía'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[inventario.models.validate_not_zero, django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
